name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install
        run: npm install
        working-directory: server
      - name: Typecheck
        run: npm run typecheck
        working-directory: server
      - name: Build
        run: npm run build
        working-directory: server
