name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install
        run: npm ci
        working-directory: server
      - name: Build macOS binary
        run: npm run build:mac
        working-directory: server
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: blink-macos
          path: server/blink-macos
      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          files: server/blink-macos
